# 포트설정(다중 서버)
server:
  port: 8080
springfox:
  documentation:
    enabled: false
spring:
  # jpa 설정
  jpa:
    hibernate:
      ddl-auto: validate 
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # RabbitMQ 설정
  rabbitmq:
    host: ${rabbitmq-uri}
    port: 5672
    username: rebook-admin
    password: "{cipher}45f14f29e5335a6fd7fd0ba53a999972027c800cb0051576ec79982a864d1ae2351f0cb575ac7e64cb1c45c3968a4d93"

# Eureka 클라이언트 설정
eureka:
  client:
    service-url:
      defaultZone: http://${eurekahost}:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: ${spring.application.name}:main

# Actuator 및 모니터링
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus # prometheus, health, info 엔드포인트 노출
  
# 로깅 설정 (예시)
logging:
  level:
    root: INFO
    org.springframework: INFO
    org.hibernate.SQL: WARN