spring:
  # =========================
  # 1. jpa 설정
  # =========================
  jpa:
    hibernate:
      ddl-auto: update # (개발: update, 운영: validate 또는 none 권장)
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # =========================
  # 2. Redis 설정
  # =========================
  redis:
    host: localhost
    port: 6379


  # =========================
  # 3. RabbitMQ 설정
  # =========================
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

# =========================
# 4. Eureka 클라이언트 설정
# =========================
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: ${spring.application.name}:main

# =========================
# 5. Actuator 및 모니터링
# =========================
management:
  endpoints:
    web:
      exposure:
        include: "*" # prometheus, health, info 엔드포인트 노출
  
# =========================
# 6. 로깅 설정 (예시)
# =========================
logging:
  level:
    root: DEBUG
    org.springframework: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
