spring:
  # 0. 데이터베이스
  datasource:
      url: jdbc:postgresql://rebook-database:5432/rebookdb
      username: junghokim
      password: 
      driverClassName: org.postgresql.Driver
  # 1. jpa 설정
  jpa:
    hibernate:
      ddl-auto: update # (개발: update, 운영: validate 또는 none 권장)
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # 2. Redis 설정
  redis:
    host: redis
    port: 6379

  # 3. RabbitMQ 설정
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

# 4. Eureka 클라이언트 설정
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: ${spring.application.name}:main

# 5. Actuator 및 모니터링
management:
  endpoints:
    web:
      exposure:
        include: "*" # 개발환경전부 보기