# 포트설정(다중 서버)
server:
  port: 8080

spring:
  # jpa 설정
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update 
    show-sql: false

  # RabbitMQ 설정
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: rebook-admin
    password: "{cipher}45f14f29e5335a6fd7fd0ba53a999972027c800cb0051576ec79982a864d1ae2351f0cb575ac7e64cb1c45c3968a4d93"

# Actuator 및 모니터링
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus # prometheus, health, info 엔드포인트 노출

# api-cods 설정
springdoc:
  api-docs:
    enabled: false