# 포트설정(단일 서버)
server:
  port: 9003

#mongodb 설정
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: rebookdb
      username: root
      password: 1234
      authentication-database: admin
