spring: 
    data:
    mongodb:
      host: mongodb
      port: 27017
      database: chatdb
      username: mongos
      password: "{cipher}1acba52d88b706d2243177e61f9585710583bf6aecb3a5cb790f55c109bdb4f338ddbc80c1019ce70b0b856bdba6105f"
      authentication-database: admin
      
# rabbitmq queue 연결
notification:
  exchange: chat.notification.exchange
  routing-key: chat.notification.key