spring: 
    data:
    mongodb:
      host: mongodb
      port: 27017
      database: chatdb
      username: mongos
      password: "{cipher}552e3cdfebf43dc228073f9b571770ad0383a57f53e0c278ec3a628f1b54ff83121d0fa251ec4a32778e691c52d4413f"
      
# rabbitmq queue 연결
notification:
  exchange: chat.notification.exchange
  routing-key: chat.notification.key