spring:
# RDS: postgresql
  datasource:
      url: jdbc:postgresql://notification-db.cdwgag0uefv1.ap-northeast-2.rds.amazonaws.com:5432/notificationdb
      username: postgres
      password: "{cipher}96be085eba17331de2d0aa80f95a097fcd50ef0ff9593a378ba46f5b93143d0b0b11e49141f2341d0bd3ebb51dd5e79e"
      driverClassName: org.postgresql.Driver
# Redis 설정
  data:
    redis:
      host: redis
      port: 6379
      password: "{cipher}b3e680e7d6952f84791800a8d402f95aff2bf236a805d0f11a249b7abd1f41890143c7fc9724cb5aeac6c67e247a6729"

# Eureka 클라이언트 설정
eureka:
  client:
    service-url:
      defaultZone: http://172.31.73.161:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    instance-id: ${spring.application.name}:main
    ip-address: 172.31.79.125
    prefer-ip-address: true