spring:
# RDS: postgresql
  datasource:
      url: jdbc:postgresql://postgresql:5432/rebooktradingdb
      username: rebook-trading-service-db
      password: "{cipher}e1a44d106a2ff47319ce13541eb48cba406d6cc7d2a95f310a4655a5802723e5aa3fc6c4c97a8bd0fb2d826fe40e45be"
      driverClassName: org.postgresql.Driver
# Redis 설정
  data:
    redis:
      host: redis
      port: 6379
      password: "{cipher}83acdec032924181aaa39e93ff2a7286867f2e8d86eec361cba9910b59954e739cc91b4984a4dd8c6aaf256cc8914e0d"