server:
  port: 8080

jwt:
  secret: ${JWT_SECRET}

sentry:
  dsn: ${SENTRY_DSN}
  send-default-pii: true

spring:
  application:
    name: rebook-gateway

  cloud:
    discovery:
      enabled: true

  profiles:
    active: dev




