# actuator 설정
management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,info

# 유레카 설정
eureka:
  client:
    service-url:
      defaultZone: http://rebook-eureka:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    instance-id: ${spring.application.name}:origin