spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://rebook-front:3001"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/users/**, /api/auths/**
        - id: rebook-book
          uri: lb://BOOK-SERVICE
          predicates:
            - Path=/api/books/**
        - id: rebook-trading
          uri: lb://TRADING-SERVICE
          predicates:
            - Path=/api/tradings/**
        - id: rebook-notification
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/api/notifications/**
        - id: rebook-chat
          uri: lb://CHAT-SERVICE
          predicates:
            - Path=/api/chats/**
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

eureka:
  client:
    service-url:
      defaultZone: http://{private-ip}:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    instance-id: ${spring.application.name}:origin

