server:
  port: 8080

jwt:
  secret: ${JWT_SECRET}
  access-expiration: 1_800_000 # 30분
  refresh-expiration: 604_800_000 # 7일

feign:
  client:
    config:
      default:
        connectTimeout: 3000
        readTimeout: 3000
        loggerLevel: basic

sentry:
  dsn: ${SENTRY_DSN}
  send-default-pii: true

spring:
  application:
    name: rebook-gateway

  data:
    redis:
      host: localhost
      port: 6379


  cloud:
    discovery:
      enabled: true

  profiles:
    active: dev




