server:
  port: 8888

spring:
  application:
    name: rebook-config

  profiles:
    active: dev

  #파일등록
  cloud:
    config:
      server:
        git:
          uri: https://github.com/gratisreise/rebook-yamls.git
          username: ${GIT_USERNAME}
          password: ${GIT_PASSWORD}
          default-label: main


#프로메테우스 접근허용
management:
  prometheus:
    metrics:
      export:
        enabled: true
#센트리 로깅
sentry:
  dsn: ${SENTRY_DSN}
  send-default-pii: true
