server:
  port: 8888

spring:

  application:
    name: config-server

  #
  profiles:
    active: dev

  #유레카 등록
  cloud:
    config:
      server:
        git:
          uri: https://github.com/rebook/config-repo
          username: ${GIT_USERNAME}
          password: ${GIT_PASSWORD}
          default-label: main

#프로메테우스 접근허용
management:
  prometheus:
    metrics:
      export:
        enabled: true