server:
  port: 8888

encrypt:
  key: ${SECRET_KEY}

spring:
  application:
    name: rebook-config

  profiles:
    active: dev

  #파일등록
  cloud:
    config:
      server:
        git:
          uri: https://github.com/gratisreise/rebook-yamls.git
          username: ${GIT_USERNAME}
          password: ${GIT_PASSWORD}
          default-label: main

#센트리 로깅
sentry:
  dsn: ${SENTRY_DSN}
  send-default-pii: true
