spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:5173"
              - "https://rebookk.click"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
              - PATCH
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: rebook-user
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/users/**, /api/auths/**
        - id: rebook-book
          uri: lb://BOOK-SERVICE
          predicates:
            - Path=/api/books/**
        - id: rebook-trading
          uri: lb://TRADING-SERVICE
          predicates:
            - Path=/api/tradings/**
        - id: rebook-notification
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/api/notifications/**
        - id: rebook-chat
          uri: lb://CHAT-SERVICE
          predicates:
            - Path=/api/chats/**, /api/ws-chat/**
        - id: rebook-chat-ws
          uri: lb:ws://CHAT-SERVICE
          predicates:
            - Path=/api/ws-chat/**
            - Header=Upgrade, websocket
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

springdoc:
  swagger-ui:
    urls:
      - name: rebook-user
        url: /api/users/v3/api-docs
      - name: rebook-book
        url: /api/books/v3/api-docs
      - name: rebook-trading
        url: /api/tradings/v3/api-docs
      - name: rebook-chat
        url: /api/chats/v3/api-docs
      - name: rebook-notification
        url: /api/notifications/v3/api-docs

eureka:
  client:
    service-url:
      defaultZone: http://rebook-eureka:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    instance-id: ${spring.application.name}:origin

