spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/users/**, /api/auths/**
        - id: rebook-book
          uri: lb://BOOK-SERVICE
          predicates:
            - Path=/api/books/**
        - id: rebook-trading
          uri: lb://TRADING-SERVICE
          predicates:
            - Path=/api/tradings/**
        - id: rebook-notification
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/api/notifications/**
        - id: rebook-chat
          uri: lb://CHAT-SERVICE
          predicates:
            - Path=/api/chats/**, /api/ws-chat/**
        - id: rebook-chat-ws
          uri: lb:ws://CHAT-SERVICE
          predicates:
            - Path=/api/ws-chat/**
            - Header=Upgrade, websocket
      discovery:
        locator:
          enabled: true
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:5173"
              - "http://host.docker.internal:5173"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
              - PATCH
            allowedHeaders: '*'
            allowCredentials: true
        add-to-simple-url-handler-mapping: true

eureka:
  client:
    service-url:
      defaultZone: http://rebook-eureka:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    instance-id: ${spring.application.name}:origin

management:
  endpoints:
    web:
      exposure:
        include: "*"